name: Prepare Delivery
runs:
  using: composite
  steps:
    - name: Ensure release tag is present
      uses: ./.github/actions/ensure_release_tag_is_present

    - name: Install tools, lint and build
      uses: ./.github/actions/install_tools_lint_and_build
