import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "link",
      label: "Demo playground",
      href: "https://cloud.car-cutter.com/web-player/v3/index.html?customer=435f524046fad7a473eaaec598d27c0a833299531af9598a3809a468d17ce145&id=DEMOVINNG360V3",
    },
    {
      type: "category",
      label: "Installation",
      link: {
        type: "generated-index",
        description:
          "The WebPlayer can be used as a Custom Element, inject with the JavaScript API, or by using one of the included frameworks adapters below.",
      },
      items: [{ type: "autogenerated", dirName: "installation" }],
    },
    "properties",
    "events",
    "styles",
    "optimization",
    {
      type: "category",
      label: "Advanced customisation",
      link: {
        type: "generated-index",
        description: "The WebPlayer can be highly customized",
      },
      items: [{ type: "autogenerated", dirName: "advanced_customisation" }],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
