name: Prepare Release Artifacts
runs:
  using: composite
  steps:
    - name: Prepare artifacts for release
      shell: bash
      run: |
        mkdir -p artifacts
        cp "packages/webplayer-script/dist/bundle-$VERSION.js" "artifacts/bundle-$VERSION.js"
        cp "packages/webplayer-script-react-16-17/dist/bundle-react-16-17@$VERSION.js" "artifacts/bundle-react-16-17@$VERSION.js"
        cp "packages/webplayer-script-react-18/dist/bundle-react-18@$VERSION.js" "artifacts/bundle-react-18@$VERSION.js"
        ls -la artifacts/
