name: Continuous Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure release tag is not present
        uses: ./.github/actions/ensure_release_tag_is_not_present

      - uses: ./.github/actions/install_tools_lint_and_build

      - name: Prepare artifacts for release
        uses: ./.github/actions/prepare_release_artifacts

      # https://github.com/marketplace/actions/create-release
      - name: Create release on GitHub
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_TAG }}
          name: "WebPlayer ${{ env.VERSION }}"
          commit: "main"
          draft: false
          makeLatest: true
          allowUpdates: true
          updateOnlyUnreleased: true
          skipIfReleaseExists: true
          prerelease: false
          artifacts: "artifacts/*.js"
          artifactContentType: "application/javascript"
          artifactErrorsFailBuild: true
          removeArtifacts: true
          replacesArtifacts: true
          generateReleaseNotes: false
          body: |
            **[Changes](https://github.com/carcutter/cars-webplayer-js/commits/@car-cutter/wc-webplayer@${{ env.VERSION }})**
