name: Continuous Delivery
on:
  release:
    types: [published]

jobs:
  docs:
    name: doc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: "main"
          fetch-tags: true

      - name: Prepare delivery
        uses: ./.github/actions/prepare_delivery

      - name: Publish documentation
        shell: bash
        env:
          GIT_PASS: ${{ secrets.GIT_PAT }}
          GIT_USER: "car-cutter"
          GIT_USER_NAME: "CarCutter"
          GIT_USER_EMAIL: "it@car-cutter.com"
          CURRENT_BRANCH: "main"
        run: yarn publish:docs

  npm:
    name: npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: "main"
          fetch-tags: true

      - name: Prepare delivery
        uses: ./.github/actions/prepare_delivery

      - name: Publish to npm
        shell: bash
        env:
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: yarn publish:packages

  cdn:
    name: cdn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: "main"
          fetch-tags: true

      - name: Prepare delivery
        uses: ./.github/actions/prepare_delivery

      - name: Prepare artifacts for release
        uses: ./.github/actions/prepare_release_artifacts

      - name: Prepare artifacts for S3 deployment
        shell: bash
        run: |
          mkdir -p artifacts
          cp "artifacts/bundle-$VERSION.js" "artifacts/bundle.js"
          cp "artifacts/bundle-react-16-17@$VERSION.js" "artifacts/bundle-react-16-17.js"
          cp "artifacts/bundle-react-18@$VERSION.js" "artifacts/bundle-react-18.js"
          ls -la artifacts/

      # https://github.com/marketplace/actions/s3-sync
      - uses: jakejarvis/s3-sync-action@master
        # with:
        #   args: --dryrun
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          AWS_S3_BUCKET: "carcutter-cdn-ireland"
          AWS_REGION: "eu-west-1"
          SOURCE_DIR: "artifacts"
          DEST_DIR: "libs/web-player/v3/"
