name: Continuous Integration
on:
  push:
    branches:
      - develop
    paths:
      - "apps/**"
      - "packages/**"
      - "schemata/**"
      - "package.json"
      - "turbo.json"
      - "yarn.lock"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/setup-yarn
      - name: Install Node.js and Yarn
        uses: mskelton/setup-yarn@v3
        with:
          node-version: "20"

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
