name: Continuous Integration
on:
  pull_request:
    paths:
      - "apps/**"
      - "packages/**"
      - "schemata/**"
      - "package.json"
      - "turbo.json"
      - "yarn.lock"
      - ".github/workflows/continuous_integration.yml"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install_tools

      - name: Lint
        run: yarn lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install_tools

      - name: Build
        run: yarn build

  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: ./.github/actions/install_tools

  #     - name: Test
  #       run: yarn test
