name: Lint Commit Messages
on: pull_request

jobs:
  commits:
    name: Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: ${{ github.workspace }}/commitlint.config.mjs
          failOnWarnings: true
